package nl.payconiq.api.utils;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

public class PropertiesReader {

	private Properties properties;
	
	/**
	 * Constructor to load the properties file generated by maven properties
	 */
	public PropertiesReader() {
		
		InputStream is = getClass().getClassLoader().getResourceAsStream("config.properties");
		this.properties = new Properties();
		
		if(is == null) {
			throw new RuntimeException("Could not find the properties file  : config.properties.");
		}
		
		try {
			this.properties.load(is);
		} catch (IOException e) {
			throw new RuntimeException("Could not read properties from file  : config.properties.");
		}
	}
	
	/**
	 * This function get property based on key name of property
	 * @author Anshika Gupta
	 * @param propertyName
	 * @return {@link String}
	 */
	public String getProperty(String propertyName) {
        return this.properties.getProperty(propertyName);
    }
}
